# Generated by Django 3.0.6 on 2020-06-06 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0004_author_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='readers',
            field=models.ManyToManyField(related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
